### PR TITLE
Normalize all colors that React Native supports

### LINKED ISSUE #52: Incomplete color normalization
### Description

The new color normalization added in #50 has broken `react-native-web` shadow styling for some colour formats.

https://github.com/jpudysz/react-native-unistyles/blob/86534364771264941c63496d32421bc1a4c04706/src/utils/normalizer.ts#L11-L13

Based on the comments in the commit it looks like it's known that it's an incomplete implementation.

I imagine to stay in-sync with what React Native itself supports, it'd make sense to add a `peerDependency` to [@react-native/normalize-colors](https://www.npmjs.com/package/@react-native/normalize-colors) which is the underlying utility library that React Native uses to pre-parse colours and then mix-in the alpha channel where required.

I'd be happy to create a PR with that implementation if that approach is suitable.

### Steps to reproduce

1. Use a `shadowColor` of `black` with an opacity of `0.5`
2. Observe output colour is `black` without opacity

### Snack or a link to a repository (optional)

_No response_

### Unistyles version

1.1.0

### React Native version

0.72.6

### Platforms

React Native Web

### PR DESCRIPTION
**Pull request by levibuzolic**
## Summary

Fixes  #52

Rather than _always_ normalizing colours, I've opted to only modify the input when required (ie. an `opacity` other than `1` is supplied) this means that the output isn't strictly as consistent, but will be faster and doesn't change the authors intent in the case an unsupported value is supplied that the browser still knows how to handle. (Like the new `color(display-p3 1 0.5 0)` formats)

Otherwise we can just pass the colour through as-is.

## Test plan

I've expanded and tweaked some of the existing tests to try to cover the new code path.

### CODE REVIEW

File: src/utils/normalizer.ts [hunk 1]
```diff
@@ -1,45 +1,39 @@
...
+    const hex = integer.toString(16).padStart(8, '0')
+
+    if (hex.length === 8) {
+        const [r = 0, g = 0, b = 0, a = 1] = hex
             .split(/(?=(?:..)*$)/)
             .map(x => parseInt(x, 16))
             .filter(num => !isNaN(num))
 
-        return `rgba(${r},${g},${b},${(a as number) / 255})`
+        return `rgba(${r},${g},${b},${((a as number) / 255) * opacity})`
```
Comment (levibuzolic) [inline src/utils/normalizer.ts:33]: A quick test on both iOS and Web shows that `shadowOpacity` is combined with the `shadowColor`'s opacity so we need to multiply the colours opacity by the desired shadow opacity.

File: src/utils/module.d.ts [hunk 2]
```diff
@@ -0,0 +1,3 @@
+declare module '@react-native/normalize-colors' {
```
Comment (levibuzolic) [inline src/utils/module.d.ts:1]: Frustratingly `@react-native/normalize-colors` doesn't have a [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) package. I'll try and chase that up, but this will work for now.

Comment (levibuzolic) [reply src/utils/module.d.ts:1]: Looks like CI isn’t happy about it. Will take another look in the morning.

File: package.json [hunk 3]
```diff
@@ -75,6 +75,7 @@
     "typescript": "5.2.2"
   },
   "peerDependencies": {
+    "@react-native/normalize-colors": "*",
```
[the remark this answers is not in the document]
Comment (levibuzolic) [reply package.json:79]: Ah of course, will need to be a `peer` for consumers and a `dev` for test.

**Review by jpudysz — APPROVED** [review]
Thanks man, and kudos for smart optimization ✋

**Comment by jpudysz** [comment]
No, it's auto installed with react native

**Comment by jpudysz** [comment]
I don't know, I need to check it. I need to import it in one file.
